Matkul API 86ep7ztjq
hmif-itb/hmif-app-be pull request #9
Opened 2024-05-07 04:46 UTC by frendysanusi05

2024-05-07 06:38 UTC, fawwazabrials requested changes

2024-05-07 06:38 UTC, fawwazabrials commented on src/types/course.types.ts
> +    example: '6',
ini jadiin integer aja yg curriculumYear sama semester biar sesuai ama db

2024-05-07 06:38 UTC, fawwazabrials commented on src/types/course.types.ts
> +export const CourseSchema = createSelectSchema(courses);
```suggestion
export const CourseSchema = createSelectSchema(courses).openapi('Course');
```

2024-05-07 09:00 UTC, frendysanusi05 commented on src/types/course.types.ts
> +    example: '6',
changes done

2024-05-08 14:58 UTC, fawwazabrials requested changes
semangat :D

2024-05-08 14:58 UTC, fawwazabrials commented on src/routes/course.route.ts
> +  operationId: 'getlistCoursesById',
ini ganti aja namanya jadi getCourseByIdRoute

2024-05-08 14:58 UTC, fawwazabrials commented on src/routes/course.route.ts
> +          schema: ListCourseSchema,
singular course aja, kan kalo by id udah pasti 1 yg direturn

2024-05-08 14:58 UTC, fawwazabrials commented on src/repositories/course.repo.ts
> +export async function getListCoursesById(db: Database, courseId: string) {
again, ganti aja namanya jadi getCourseById

2024-05-08 14:58 UTC, fawwazabrials commented on src/repositories/course.repo.ts
> +  const where = and(courseIdQ);
apus aja karena cuma ada 1 where condition

2024-05-08 14:58 UTC, fawwazabrials commented on src/repositories/course.repo.ts
> +    where,
ini langsung diganti one liner yg eq() aja

2024-05-08 14:58 UTC, fawwazabrials commented on src/controllers/course.controller.ts
> +        error: 'Something went wrong',
jangan lupa buat handle kasus id not found

2024-05-08 14:58 UTC, fawwazabrials commented on src/routes/course.route.ts
> +          schema: CourseSchema.omit({ id: true }),
ini buat body-nya harusnya optional semua aja, soalnya kan bisa aja user cuma pengen update major aja atau name aja gitu

2024-05-08 14:58 UTC, fawwazabrials commented on src/repositories/course.repo.ts
> +      .set(data)
jangan lupa handle kasus kalo data yg diubah cuma 1 attribut aja

2024-05-08 14:58 UTC, fawwazabrials commented on src/controllers/course.controller.ts
> +    return c.json(err, 400);
handle kasus kalo id not found secara terpisah

2024-05-08 14:58 UTC, fawwazabrials commented on src/controllers/course.controller.ts
> +    return c.json(err, 400);
handle kasus kalo id not found secara terpisah

2024-05-11 06:56 UTC, fawwazabrials approved these changes

2024-05-11 06:57 UTC, fawwazabrials commented
LGTM!

2024-05-11 06:57 UTC, merged